@startuml

actor Verifier

participant VerificationServer as VS

database VerificationDataStore as VSDS

Verifier -> VS: Authentication Request (with username and password) and original url
VS -> VSDS: checks username and password
alt Valid credentials
    VS -> Verifier: JWT Token + redirection to original url
else Invalid credentials:
    VS -> Verifier: Error + SELF URL
end

@enduml