@startuml
autonumber

actor Initiator
participant EntryPoint as EP
participant VerificationServer as VS
database VerificationDataStore as VSDS
participant Web
participant Verifier
participant Channel

Initiator -> EP: Request verification
note right
- Initiator identification
- language
- supported channels (conversation)
- supports details registration (if not: accessible URL to see details)
endnote
alt request not valid (several reasons)
    EP -> Initiator: Invalid request
else request trusted (with Initiator idenntifier available)
    EP -> VS: Creates verification session POST /api/sessions
    VS -> VSDS: Stores verification session
    alt verification allows registering details in our datastore
        VS -> EP: Send verification details request
        EP -> Initiator: Sends detail request
        Initiator -> Web: Provides verification details
        Web -> VS: Submit verification details POST /api/sessions/{sessionId}/details
        VS -> VSDS: Stores verification details
    else verification does not allow registering details
        VS -> Unknown: Access details to check existence ?
        VS -> VSDS: Store access details
    end
    VS -> Verifier: Request verification conversation (providing options)
    ... some minutes later ....
    Verifier -> VS: Creates verification conversation with preferred option (e.g. Channel)
    note right
    Verifier can be a verified volunteer
    behind a web cam but can also be a machine
    offering a verification API
    endnote
    VS -> EP: Request Initiator availability for verification
    EP -> Initiator: Request Initiator availability
    ... some minutes later ...
    alt Initiator available
        Initiator -> EP: Accepts verification conversation
        EP -> VS: Adds Initiator to conversation
        VS -> Verifier: Sends verification details access
        Verifier -> Web: Access verification details
        Web -> VS: Access verification details
        VS -> VSDS: Audits access to the verification details
        alt Verifier uses WebRtc as Channel
            VS -> WebRtc: Create channel for verification conversation
            WebRtc -> VS: Return conversation channel details
        else verifier uses other means
            VS -> Unknown: Create channel for verification conversation
            Unknown -> VS: Return conversation channel details
            note left
            Verifier could decide to use other
            means to have a conversation, such as:
            Telegram
            ...
            endnote
        end
        VS -> Verifier: Sends conversation channel details
        VS -> EP: Sends conversation channel details
        EP -> Initiator: Send message with conversation link
        alt Verifier uses Channel
            Verifier -> Channel: Join Room
            Initiator -> Channel: Join Room
        else Verifier uses other means
            Verifier -> Unknown: Join channel
            Initiator -> Unknown: Join channel
        end
        Verifier -> VS: Send verification result
        VS -> VSDS: Stores verification result (audited)
        VS -> EP: Send verification result
        note right
        Verification result may include
        VS private key signed message
        including own generated identifier
        used to consult identity of the Initiator
        (Can be transformed in a QRCode)
        endnote
        EP -> Initiator: Send verification result
    else Initiator not available (or does not respond in x time)
        EP -> VS: Initiator not available
        VS -> Verifier: suspends verification
    else Initiator rejects verification
        Initiator -> EP: Rejects verification call
        EP -> VS: calls off verification
        VS -> Verifier: terminates verification
    end
end

@enduml